/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error": "#ba1a1a",
        "surface-container-low": "#eff4ff",
        "background": "#f8f9ff",
        "on-tertiary-fixed": "#00201d",
        "primary-fixed": "#dae2ff",
        "primary-container": "#0055cc",
        "on-primary": "#ffffff",
        "surface-bright": "#f8f9ff",
        "tertiary-container": "#006960",
        "on-error-container": "#93000a",
        "on-secondary": "#ffffff",
        "secondary": "#a43073",
        "on-primary-container": "#c8d5ff",
        "on-background": "#0b1c30",
        "on-error": "#ffffff",
        "surface-variant": "#d3e4fe",
        "outline-variant": "#c3c6d6",
        "on-secondary-fixed-variant": "#85145a",
        "on-surface": "#0b1c30",
        "surface-container-highest": "#d3e4fe",
        "on-surface-variant": "#424654",
        "outline": "#737785",
        "on-primary-fixed-variant": "#00419f",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#dce9ff",
        "tertiary-fixed-dim": "#6bd8cb",
        "error-container": "#ffdad6",
        "primary": "#003f9c",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#001947",
        "inverse-surface": "#213145",
        "on-secondary-container": "#76014e",
        "surface": "#f8f9ff",
        "secondary-container": "#fc79bd",
        "surface-dim": "#cbdbf5",
        "on-tertiary-fixed-variant": "#005049",
        "inverse-on-surface": "#eaf1ff",
        "on-tertiary-container": "#7ce9db",
        "surface-container": "#e5eeff",
        "primary-fixed-dim": "#b1c5ff",
        "tertiary": "#004f48",
        "surface-tint": "#0657ce",
        "tertiary-fixed": "#89f5e7",
        "on-secondary-fixed": "#3d0026",
        "inverse-primary": "#b1c5ff",
        "secondary-fixed": "#ffd8e7",
        "secondary-fixed-dim": "#ffafd3"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "base": "4px",
        "gutter": "24px",
        "stack-lg": "32px",
        "stack-md": "16px",
        "margin-mobile": "16px",
        "container-max": "1280px",
        "stack-sm": "8px"
      },
      fontFamily: {
        "data-metric": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-mono": ["JetBrains Mono", "monospace"],
        "headline-sm": ["Inter", "sans-serif"]
      },
      fontSize: {
        "data-metric": ["20px", { "lineHeight": "1.0", "fontWeight": "700" }],
        "body-lg": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "display-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "body-md": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "label-mono": ["12px", { "lineHeight": "1.0", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "headline-sm": ["18px", { "lineHeight": "1.4", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
